build_test:
  stage: test
  script:
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - cd dist
    - zip -r dist.zip ./*
  only:
    - master
  when: always
  artifacts:
    paths:
      - dist/dist.zip
    expire_in: 1 week